version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  jobs:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'website'
    build: .
    command: bash start_jobs.sh
    volumes:
      - '.:/hack2save'
    volumes_from:
      - box

  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/hack2save'
    volumes_from:
    - box

  box:
    image: busybox
    volumes:
      - /box

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

volumes:
  redis:
  postgres:
  box:
